[package]
name = "ga_core"
version = "0.1.0"
authors = ["Michael Byrne <16238945+MichaelByrneAU@users.noreply.github.com>"]
edition = "2018"

[dependencies]
num = "0.2.0"

[dev-dependencies]
assert_approx_eq = "1.1.0"